/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sina.view.formularios;

import com.sina.view.controles.ControlFormSistema;
import javax.swing.JButton;

/**
 *
 * @author ritacosta
 */
public class Sistema extends javax.swing.JFrame {

    public ControlFormSistema control;
    
    public Sistema() {
        initComponents();
        setLocationRelativeTo(null);
        control = new ControlFormSistema(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneSistema = new javax.swing.JDesktopPane();
        btTestPrestador = new javax.swing.JButton();
        btnProcedimento = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btTestPrestador.setText("Prestador");
        jDesktopPaneSistema.add(btTestPrestador);
        btTestPrestador.setBounds(0, 0, 100, 23);

        btnProcedimento.setText("Procedimento");
        jDesktopPaneSistema.add(btnProcedimento);
        btnProcedimento.setBounds(100, 0, 100, 23);

        btnPacientes.setText("Pacientes");
        jDesktopPaneSistema.add(btnPacientes);
        btnPacientes.setBounds(200, 0, 100, 23);

        jButton4.setText("jButton4");
        jDesktopPaneSistema.add(jButton4);
        jButton4.setBounds(300, 0, 100, 23);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTestPrestador;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnProcedimento;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPaneSistema;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtTestPrestador() {
        return btTestPrestador;
    }

    public void setBtTestPrestador(javax.swing.JButton btTestPrestador) {
        this.btTestPrestador = btTestPrestador;
    }

    public javax.swing.JDesktopPane getjDesktopPaneSistema() {
        return jDesktopPaneSistema;
    }

    public void setjDesktopPaneSistema(javax.swing.JDesktopPane jDesktopPaneSistema) {
        this.jDesktopPaneSistema = jDesktopPaneSistema;
    }

    public javax.swing.JButton getBtnProcedimento() {
        return btnProcedimento;
    }

    public void setBtnProcedimento(javax.swing.JButton btnProcedimento) {
        this.btnProcedimento = btnProcedimento;
    }

    public JButton getBtnPacientes() {
        return btnPacientes;
    }

    public void setBtnPacientes(JButton btnPacientes) {
        this.btnPacientes = btnPacientes;
    }

    

}
